name: dcnpa
channels:
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py311h06a4308_0
  - aiohttp=3.11.10=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=h865e1df_2
  - attrs=24.3.0=py311h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - datasets=3.3.2=py311h06a4308_0
  - dill=0.3.8=py311h06a4308_0
  - frozenlist=1.5.0=py311h5eee18b_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - huggingface_hub=0.29.2=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.12.1=hc9e6f67_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libprotobuf=5.29.3=hc99497a_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libuuid=1.41.5=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - multidict=6.1.0=py311h5eee18b_0
  - multiprocess=0.70.15=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy-base=2.0.1=py311hf175353_1
  - openssl=3.0.16=h5eee18b_0
  - orc=2.1.1=hd396ef6_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - pip=25.0=py311h06a4308_0
  - propcache=0.3.1=py311h5eee18b_0
  - protobuf=5.29.3=py311he621ea3_0
  - pyarrow=19.0.0=py311h6a678d5_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h5eee18b_0
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.5.3=py311h448de89_0
  - setuptools=75.8.0=py311h06a4308_0
  - six=1.17.0=py311h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py311h5e3497e_0
  - tqdm=4.67.1=py311h92b7b1e_0
  - transformers=4.49.0=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.45.1=py311h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py311h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - asttokens==3.0.0
      - biopython==1.85
      - blessed==1.20.0
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.59.2
      - fsspec==2024.6.1
      - gpustat==1.1.1
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.9
      - llvmlite==0.44.0
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.61.2
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.28.3
      - nvidia-nvtx-cu11==11.8.86
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.7
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyzmq==26.3.0
      - scikit-learn==1.6.1
      - scikit-multilearn==0.2.0
      - scipy==1.15.2
      - shap==0.48.0
      - slicer==0.0.8
      - stack-data==0.6.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0+cu118
      - torch-geometric==2.6.1
      - torchaudio==2.6.0+cu118
      - torchinfo==1.8.0
      - torchsummary==1.5.1
      - torchvision==0.21.0+cu118
      - tornado==6.4.2
      - traitlets==5.14.3
      - triton==3.2.0
      - typing-extensions==4.13.0
      - wcwidth==0.2.13
      - xgboost==3.0.5
prefix: /data1/chenshutao/anaconda3/envs/dcnpa
